advertisements/urls.py
from django.contrib import admin
from django.urls import path
from advertisements.views import StartView, CarsView, ArticleView
from users.views import GetModels, get_car_brands, get_generations

app_name = "advertisements"

urlpatterns = [
    path('', StartView.as_view(), name='start'),
    path('cars/', CarsView.as_view(), name='cars'),
    path('article/<int:pk>', ArticleView.as_view(), name='article'),
    path('get_models/', GetModels.as_view(), name='get_models'),
    path('get_car_brands/', get_car_brands, name='get_car_brands'),
    path('get_generations/', get_generations, name='get_generations'),
]

kursovaya/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
# from advertisements.views import start

urlpatterns = [
    path('', include('advertisements.urls', namespace='advertisements')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import (
    logout, GetModels,
    get_car_brands, get_generations,
    EditCarView, DeleteCarView, LoginUser, Registration, ProfileView,
    delete_photo, CreateCarView,
    UserProfileEditView)  # , login, registration, profile,  GetModelsView, GetGenerationsView,

app_name = 'users'
urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('registration/', Registration.as_view(), name='registration'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('logout/', logout, name='logout'),
    path('create_post/', CreateCarView.as_view(), name='create_post'),
    path('get_models/', GetModels.as_view(), name='get_models'),
    path('get_car_brands/', get_car_brands, name='get_car_brands'),
    path('get_generations/', get_generations, name='get_generations'),
    # path('update_models/', GetModelsView.as_view(), name='update_models'),
    # path('update_generations/', GetGenerationsView.as_view(), name='update_generations'),
    path('edit/<int:pk>', EditCarView.as_view(), name='edit_car'),
    path('delete_car/<int:pk>', DeleteCarView.as_view(), name='delete_car'),
    path('delete_photo/<int:image_id>', delete_photo, name='delete_photo'),
    path('edit_profile/<int:pk>', UserProfileEditView.as_view(), name='edit_profile'),

]

advertisements/models.py
from datetime import datetime

from django.db import models

from users.models import User


class CarBrand(models.Model):
    brand = models.CharField(max_length=100)

    def __str__(self):
        return self.brand


class CarModel(models.Model):
    brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    model = models.CharField(max_length=100)

    def get_model(self):
        return self.model

    def __str__(self):
        return f'{self.model}'


class CarGeneration(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    generation = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.generation}'


class Car(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, default=None)
    generation = models.ForeignKey(CarGeneration, on_delete=models.CASCADE, default=None)
    release_year = models.IntegerField(default=0)
    mileage = models.IntegerField(default=0)
    color = models.CharField(default='black')
    created_timestamp = models.DateTimeField(auto_now_add=True)

    description = models.TextField()
    price = models.DecimalField(max_digits=15, decimal_places=2)

    def __str__(self):
        return f'{self.brand} {self.model} by: {self.username}'


class Image(models.Model):
    car = models.ForeignKey(Car, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to="images/")

    def __str__(self):
        return f'{self.car.brand} {self.car.model} by: {self.car.username}'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    phone_number = models.CharField(max_length=20)

    def get_fullname(self):
        return self.first_name + self.last_name

users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, Submit, HTML
from django import forms

from datetime import timedelta
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)
from django.utils.timezone import now

from users.models import User
from advertisements.models import Car, Image, CarBrand, CarModel, CarGeneration


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': "Введите имя пользователя"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите имя"}))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите фамилию"}))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите имя пользователя"}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите адрес эл. почты"}))

    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': "Введите номер телефона"}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone_number', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        expiration = now() + timedelta(hours=48)
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}, ))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email', 'phone_number')


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ('brand', 'model', 'release_year', 'mileage', 'color', 'price', 'description')


class ImageCreationForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('images',)


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['brand', 'model', 'mileage', 'color', 'price', 'description']

    def __init__(self, *args, **kwargs):
        super(CarForm, self).__init__(*args, **kwargs)
        self.fields['brand'].widget.attrs['id'] = 'id_brand'
        self.fields['model'].widget.attrs['id'] = 'id_model'


class CarEditForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['mileage', 'color', 'price', 'description']


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number']

users/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin

from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import auth
from django.views import View
from django.views.generic import UpdateView, DeleteView, TemplateView, DetailView
from django.views.generic.edit import CreateView

from advertisements.models import Car, Image, CarBrand, CarModel, CarGeneration
from common.views import TitleMixin
from users.forms import UserRegistrationForm, UserLoginForm, UserProfileForm, PostCreationForm, ImageCreationForm, \
    CarForm, CarEditForm, UserProfileEditForm
from users.models import User

from django.core import serializers


class LoginUser(TitleMixin, View):
    template_name = 'login.html'
    title = 'Авторизация'

    def get(self, request):
        form = UserLoginForm()
        context = {
            'form': form,
            'title': "CarSell - Авторизация",
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('advertisements:cars'))
        print(form.errors)
        context = {
            'form': form,
            'title': "CarSell - Авторизация",
        }
        return render(request, self.template_name, context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('advertisements:cars'))


class Registration(TitleMixin, View):
    template_name = 'registration.html'

    def get(self, request):
        form = UserRegistrationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            print(request.POST)
            form.save()
            # login(request, user)
            return HttpResponseRedirect(reverse('advertisements:cars'))

        return render(request, self.template_name, {'form': form})


class ProfileView(View):
    template_name = 'profile.html'
    model = User

    def get(self, request, pk=None):
        print(request.path)
        if not pk:
            pk = request.user.id
        print(pk, self.request.user.id)

        user = get_object_or_404(User, pk=pk)
        form = UserProfileForm(instance=user)
        advertisements = Car.objects.filter(username=user)
        owner_id = advertisements.first().username.id if advertisements else 0

        # is_owner = request.user.id == owner_id
        is_owner = self.request.user.id == pk
        context = {
            'form': form,
            'advertisements': advertisements,
            'user_id': owner_id,
            'is_owner': is_owner,
        }

        return render(request, self.template_name, context)


class GetModels(View):
    def get(self, request):
        brand_id = request.GET.get('brand_id')
        print(brand_id)
        if brand_id is not None:
            models = CarModel.objects.filter(brand=brand_id)
            model_data = [{'id': model.id, 'name': model.get_model()} for model in models]
            print(model_data)
            return JsonResponse({'models': model_data})
        else:
            return JsonResponse({'error': 'Выберите бренд'}, status=400)


def get_car_brands(request):
    car_brands = CarBrand.objects.all()
    data = {'brands': [{'id': brand.id, 'name': brand.brand} for brand in car_brands]}
    return JsonResponse(data)


def get_generations(request):
    model_id = request.GET.get('model_id')
    if model_id is not None:
        generations = CarGeneration.objects.filter(model=model_id)
        # print(generations)
        data = [{'id': generation.id, 'name': generation.generation} for generation in generations]
        # print(data)
        return JsonResponse({'generations': data})


class CreateCarView(CreateView):
    model = Car
    form_class = CarEditForm
    template_name = 'create_post.html'
    success_url = '/advertisements/cars/'

    def get(self, request, *args, **kwargs):
        return render(request, 'create_post.html', context={})

    def post(self, request, *args, **kwargs):
        print(self.request.POST, 'request')

        # response = super().form_valid(form)

        car = Car.objects.create(username=self.request.user, brand=CarBrand.objects.get(id=self.request.POST['brand']),
                                 model=CarModel.objects.get(id=self.request.POST['model']),
                                 generation=CarGeneration.objects.get(id=self.request.POST['generations']),
                                 release_year=self.request.POST['release_year'], mileage=self.request.POST['mileage'],
                                 color=self.request.POST['mileage'], description=self.request.POST['description'],
                                 price=self.request.POST['price'])
        car.save()
        print(car, 'carcarcar')
        multiple_images = self.request.FILES.getlist('photos')
        print(multiple_images, 'multiple_images')
        for img in multiple_images:
            image = Image.objects.create(car=car, images=img)
            image.save()

        return redirect(reverse('advertisements:cars'))


class EditCarView(TitleMixin, UserPassesTestMixin, UpdateView):
    model = Car
    form_class = CarEditForm
    template_name = 'edit_post.html'
    title = "CarSell - Редактирование объявления"

    def test_func(self):
        return self.request.user == self.get_object().username

    def get_success_url(self):
        user_profile_url = reverse('users:profile', kwargs={'pk': self.request.user.id})

        return user_profile_url

    def form_valid(self, form):
        response = super().form_valid(form)

        print('form form form')
        print(self.request.FILES, 'files')
        print(self.model.pk)
        for f in self.request.FILES.getlist('photos'):
            print(f)
            data = f.read()
            image = Image.objects.create(car=self.object, images=f)
            image.save()
        return redirect(reverse('advertisements:cars'))
        # return response


class DeleteCarView(UserPassesTestMixin, View):

    def test_func(self):
        car = get_object_or_404(Car, pk=self.kwargs['pk'])
        return self.request.user == car.username

    def get(self, request, pk):
        car = get_object_or_404(Car, pk=pk)

        car.delete()

        return HttpResponseRedirect(reverse('users:profile', kwargs={'pk': request.user.id}))


class UserProfileEditView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'edit_profile.html'

    def test_func(self):
        return self.request.user.id == self.kwargs.get('pk')

    def get(self, request, *args, **kwargs):
        print(self.kwargs.get('pk'), self.request.user.id)
        form = UserProfileEditForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UserProfileEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('users:profile', kwargs={'pk': request.user.id}))

        return render(request, self.template_name, {'form': form})


def delete_photo(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    car_id = image.car.id
    image.delete()
    return redirect('users:edit_car', pk=car_id)

users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <meta http-equiv="Content-Type">
</head>

<body>
<div class="header">
    <div class="header_section">
        <div class="header_item headerlogo">
            <a href="#">CarSell</a>
        </div>

    </div>
    <div class="header_section">
        {% if user.is_authenticated %}
            <div class="header_item headerbutton"><a href="{% url 'users:profile' %}">Профиль: {{ user.username }}</a>
            </div>
            <div class="header_item headerbutton"><a href="{% url 'users:logout' %}">Выйти</a></div>
        {% else %}
            <div class="header_item headerbutton"><a href="{% url 'users:registration' %}">Регистрация</a></div>
            <div class="header_item headerbutton"><a href="{% url 'users:login' %}">Войти</a></div>
        {% endif %}

    </div>

</div>

{% block main %} {% endblock %}

users/templates/create_post.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Create Advertisement</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>

{% block main %}
    <div class="main">
        <div class="create-advertisement">

            <h1>Создание объявления</h1>


            <form class="create-post" method="post" enctype="multipart/form-data"
                  action="{% url 'users:create_post' %}">
                {% csrf_token %}
                <label for="brand">Бренд:</label>
                <select style="color:black" id="brand" name="brand">
                    <option value="">Выберите бренд</option>

                </select>
                <br>
                <label for="model">Модель:</label>
                <select id="model" name="model">
                    <option value="">Выберите модель</option>

                </select>

                <label for="generations">Поколение:</label>
                <select id="generations" name="generations">
                    <option value="">Выберите поколение</option>

                </select>

                <div class="advertisement-field">
                    <label for="release_year">Год выпуска:</label>
                    <input type="number" id="release_year" name="release_year" required>
                </div>

                <div class="advertisement-field">
                    <label for="color">Цвет:</label>
                    <input type="text" id="color" name="color" required>
                </div>

                <div class="advertisement-field">
                    <label for="mileage">Пробег (в км):</label>
                    <input type="number" id="mileage" name="mileage" required>
                </div>

                <div class="advertisement-field">
                    <label for="description">Описание:</label>
                    <textarea id="description" name="description" required></textarea>
                </div>

                <div class="advertisement-field">
                    <label for="price">Цена (в долларах):</label>
                    <input type="number" id="price" name="price" required>
                </div>

                <div class="advertisement-field">
                    <label for="photos">Фото, которые будут отображены в объявлении (Первое фото будет главным):</label>
                    <input type="file" id="photos" name="photos" multiple required>
                </div>

                <div class="advertisement-field">
                    <input type="submit" value="Создать">
                </div>


            </form>

            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

            <script>
                $(document).ready(function () {
                    $.ajax({
                        url: '{% url "users:get_car_brands" %}',
                        dataType: 'json',
                        success: function (data) {
                            var brandSelect = $('#brand');
                            brandSelect.empty();
                            {#console.log(data.brands)#}
                            brandSelect.append($('<option>', {
                                text: 'Выберите бренд',
                                disabled: true,
                                selected: true
                            }));
                            for (var i = 0; i < data.brands.length; i++) {
                                brandSelect.append($('<option>', {
                                    value: data.brands[i].id,
                                    text: data.brands[i].name
                                }));
                            }
                        }
                    });

                    $('#brand').on('change', function () {
                        var selectedBrand = $(this).val();


                        var url = '{% url "users:get_models" %}';
                        $.ajax({
                            url: url,
                            data: {
                                'brand_id': selectedBrand
                            },
                            dataType: 'json',
                            success: function (data) {
                                var modelSelect = $('#model');
                                modelSelect.empty();
                                modelSelect.append($('<option>', {
                                    text: 'Выберите модель',
                                    disabled: true,
                                    selected: true
                                }));
                                for (var i = 0; i < data.models.length; i++) {
                                    modelSelect.append($('<option>', {
                                        value: data.models[i].id,
                                        text: data.models[i].name
                                    }));
                                }
                            }
                        });
                    });
                    $('#model').on('change', function () {
                        var selectedModel = $(this).val();
                        console.log(selectedModel);

                        var url = '{% url "users:get_generations" %}';
                        $.ajax({
                            url: url,
                            data: {
                                'model_id': selectedModel
                            },
                            dataType: 'json',
                            success: function (data) {
                                var generations = $('#generations');
                                console.log(data, 'data');
                                generations.empty();
                                generations.append($('<option>', {
                                    text: 'Выберите поколение',
                                    disabled: true,
                                    selected: true
                                }));
                                for (var i = 0; i < data.generations.length; i++) {
                                    console.log(data.generations[i], 'iii')
                                    generations.append($('<option>', {
                                        value: data.generations[i].id,
                                        text: data.generations[i].name
                                    }));
                                }

                            }
                        });
                    });
                });
            </script>


        </div>
    </div>
{% endblock %}

</body>
</html>

users/templates/edit_post.html
{% extends 'base.html' %}

{% block main %}
    <div class="main">
        <div class="create-advertisement">

            {#    <div class="edit-advertisement">#}
            <h1>Редактировать объявление</h1>
            <form method="post" enctype="multipart/form-data" class="edit-post-form">
                {% csrf_token %}

                <div class="advertisement-field">
                    <label for="release_year">Год выпуска:</label>
                    {{ form.release_year }}
                </div>

                <div class="advertisement-field">
                    <label for="mileage">Пробег (в км):</label>
                    {{ form.mileage }}
                </div>

                <div class="advertisement-field">
                    <label for="color">Цвет:</label>
                    {{ form.color }}
                </div>

                <div class="advertisement-field">
                    <label for="description">Описание:</label>
                    {{ form.description }}
                </div>

                <div class="advertisement-field">
                    <label for="price">Цена (в долларах):</label>
                    {{ form.price }}
                </div>
                <div class="advertisement-field">
                    <label for="photos">Добавить новые фото:</label>
                    <input type="file" id="photos" name="photos" multiple>
                </div>

                <div class="advertisement-field">
                    <label>Загруженные Фотографии:</label>
                    {% for image in form.instance.image_set.all %}
                        <div class="image-container">
                            <img src="{{ image.images.url }}" alt="Car Photo" class="car-photo">
                            <div class="delete-button">
                                <a href="{% url 'users:delete_photo' image.id %}">Удалить</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <button type="submit" class="edit-advertisement">Сохранить изменения</button>


            </form>
        </div>
    </div>
    {#            </div>#}
{% endblock %}

users/templates/edit_profile.html
{% extends 'base.html' %}

{% block main %}
    <div class="create-advertisement">
        <h1>Изменение личных данных пользователя</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}


            <div class="advertisement-field">
                <label for="description">Имя:</label>
                {{ form.first_name }}
            </div>

            <div class="advertisement-field">
                <label for="description">Фамилия:</label>
                {{ form.last_name }}
            </div>

            <div class="advertisement-field">
                <label for="description">Почта:</label>
                {{ form.email }}
            </div>

            <div class="advertisement-field">
                <label for="description">Номер телефона:</label>
                {{ form.phone_number }}
            </div>

            <button type="submit" class="edit-advertisement">Сохранить изменения</button>

{#            {{ form.as_p }}#}
{#            <button type="submit">Save Changes</button>#}
        </form>
    </div>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <main>

        <div class="form-container">
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <h2>Вход</h2>

                {% if form.non_field_errors %}
                    <div class="error-message">
                        {{ form.non_field_errors }}

                    </div>
                {% endif %}


                <div class="form-field">
                    <label for="username">Имя пользователя</label>
                    <input type="text" name="username" id="username" placeholder="Имя пользователя" required>
                </div>

                <div class="form-field">
                    <label for="password">Пароль</label>
                    <input type="password" name="password" id="password" placeholder="Пароль" required>
                </div>


                <div class="form-field">
                    <input type="submit" value="Войти">
                </div>
            </form>
        </div>
    </main>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>User Profile</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <meta http-equiv="Content-Type">
</head>

<body>

{% block main %}
    <div class="main">
        <div class="user-profile">
            <h1 style="color:black">Профиль</h1>
            <div class="user-info">
{#                <h2>Имя пользователя: {{ form.username }}</h2>#}
                <h2>Имя: {{ form.first_name }}</h2>
                <h2>Фамилия: {{ form.last_name }}</h2>
                <h2>Почта: {{ form.email }}</h2>
                <h2>Телефон: {{ form.phone_number }}</h2>
            </div>

            {% if is_owner == 1 %}
                <div class="button-container">
                    <a class="profile_create_adv_button" href="{% url 'users:edit_profile' user.id%}">Изменить Профиль</a>
                </div>

                <div class="button-container">
                    <a class="profile_create_adv_button" href="{% url 'users:create_post' %}">Создать объявление</a>
                </div>
            {% endif %}

            <div class="user-advertisements">
                {% if is_owner == 1 %}
                    <h2>Ваши объявления:</h2>
                {% else %}
                    <h2>Объявления пользователя:</h2>
                {% endif %}

                {% for adv in advertisements %}
                    <div class="advertisement">
                        <a href="{% url 'advertisements:article' adv.id %}">
                            <h3>{{ adv.brand }} {{ adv.model }}</h3>
                        </a>
                        <p>{{ adv.price }}$</p>

                        {% if is_owner == 1 %}
                            <div class="button-group">
                                <div class="change-button">
                                    <a href="{% url 'users:edit_car' adv.id %}">Изменить</a>
                                </div>
                                <div class="change-button">
                                    <a href="{% url 'users:delete_car' adv.id %}">Удалить</a>
                                </div>
                            </div>
                        {% else %}
                        {% endif %}

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}
</body>
</html>