advertisements/urls.py
from django.contrib import admin
from django.urls import path
from advertisements.views import StartView, CarsView, ArticleView
from users.views import GetModels, get_car_brands, get_generations

app_name = "advertisements"

urlpatterns = [
    path('', StartView.as_view(), name='start'),
    path('cars/', CarsView.as_view(), name='cars'),
    path('article/<int:pk>', ArticleView.as_view(), name='article'),
    path('get_models/', GetModels.as_view(), name='get_models'),
    path('get_car_brands/', get_car_brands, name='get_car_brands'),
    path('get_generations/', get_generations, name='get_generations'),
]

kursovaya/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
# from advertisements.views import start

urlpatterns = [
    path('', include('advertisements.urls', namespace='advertisements')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import (
    logout, GetModels,
    get_car_brands, get_generations,
    EditCarView, DeleteCarView, LoginUser, Registration, ProfileView,
    delete_photo, CreateCarView,
    UserProfileEditView)  # , login, registration, profile,  GetModelsView, GetGenerationsView,

app_name = 'users'
urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('registration/', Registration.as_view(), name='registration'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('logout/', logout, name='logout'),
    path('create_post/', CreateCarView.as_view(), name='create_post'),
    path('get_models/', GetModels.as_view(), name='get_models'),
    path('get_car_brands/', get_car_brands, name='get_car_brands'),
    path('get_generations/', get_generations, name='get_generations'),
    # path('update_models/', GetModelsView.as_view(), name='update_models'),
    # path('update_generations/', GetGenerationsView.as_view(), name='update_generations'),
    path('edit/<int:pk>', EditCarView.as_view(), name='edit_car'),
    path('delete_car/<int:pk>', DeleteCarView.as_view(), name='delete_car'),
    path('delete_photo/<int:image_id>', delete_photo, name='delete_photo'),
    path('edit_profile/<int:pk>', UserProfileEditView.as_view(), name='edit_profile'),

]

advertisements/models.py
from datetime import datetime

from django.db import models

from users.models import User


class CarBrand(models.Model):
    brand = models.CharField(max_length=100)

    def __str__(self):
        return self.brand


class CarModel(models.Model):
    brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    model = models.CharField(max_length=100)

    def get_model(self):
        return self.model

    def __str__(self):
        return f'{self.model}'


class CarGeneration(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    generation = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.generation}'


class Car(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, default=None)
    generation = models.ForeignKey(CarGeneration, on_delete=models.CASCADE, default=None)
    release_year = models.IntegerField(default=0)
    mileage = models.IntegerField(default=0)
    color = models.CharField(default='black')
    created_timestamp = models.DateTimeField(auto_now_add=True)

    description = models.TextField()
    price = models.DecimalField(max_digits=15, decimal_places=2)

    def __str__(self):
        return f'{self.brand} {self.model} by: {self.username}'


class Image(models.Model):
    car = models.ForeignKey(Car, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to="images/")

    def __str__(self):
        return f'{self.car.brand} {self.car.model} by: {self.car.username}'

advertisements/forms.py
from django import forms

from advertisements.models import Car


class FilterForm(forms.Form):
    min_price = forms.DecimalField(widget=forms.NumberInput())
    max_price = forms.DecimalField(widget=forms.NumberInput())

    class Meta:
        fields = ('min_price', 'max_price')

advertisements/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView, UpdateView

from advertisements.forms import FilterForm
from advertisements.models import Car, Image, CarBrand, CarModel, CarGeneration
from common.views import TitleMixin


class StartView(TitleMixin, TemplateView):

    def get(self, request, *args, **kwargs):
        if not bool(request.GET):
            return render(request, 'start.html', context={'title': "CarSell - Начальная страница"})

        brand_id = request.GET.get('brand')
        model_id = request.GET.get('model')
        generation_id = request.GET.get('generations')
        release_year = request.GET.get('release_year')
        mileage = request.GET.get('mileage')
        return redirect('index.html', brand=brand_id, model=model_id, generation=generation_id,
                        release_year=release_year, mileage=mileage)


class CarsView(TitleMixin, ListView):
    model = Car
    template_name = "index.html"
    title = 'CarSell - Объявления'

    def get_queryset(self):
        brand_id = self.request.GET.get('brand')
        model_id = self.request.GET.get('model')
        generation_id = self.request.GET.get('generations')
        release_year = self.request.GET.get('release_year')
        mileage = self.request.GET.get('mileage')
        price_from = self.request.GET.get('price_from')
        price_to = self.request.GET.get('price_to')
        print(price_from, 'price_from')
        print(price_to, 'price_to')
        cars = Car.objects.all()

        if brand_id:
            car_brand = CarBrand.objects.get(id=brand_id)
            cars = cars.filter(brand=car_brand)

        if model_id:
            cars = cars.filter(model__id=model_id)

        if generation_id:
            cars = cars.filter(generation__id=generation_id)

        if release_year:
            cars = cars.filter(release_year=release_year)

        if mileage:
            cars = cars.filter(mileage=mileage)

        if price_from:
            cars = cars.filter(price__gte=price_from)

        if price_to:
            cars = cars.filter(price__lte=price_to)

        # print(cars, 'cars')
        queryset = []

        for car in cars:
            # print(car, 'car')
            image = Image.objects.filter(car=car).first()
            queryset.append([car, image])

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        # print(queryset, 'context_data')
        if len(queryset) >= 0:
            context['data'] = queryset
            return context
        # print('using this, renault')
        data = []
        for car in Car.objects.all():
            image = Image.objects.filter(car=car).first()
            data.append([car, image])
        # form = FilterForm()
        # context = super().get_context_data(**kwargs)
        context['data'] = data
        # context['form'] = form

        return context


class ArticleView(TitleMixin, TemplateView):
    template_name = 'article.html'
    title = 'Объявление'

    def get_context_data(self, pk, **kwargs):
        car = Car.objects.get(pk=pk)
        username_id = car.username_id
        # print(username_id, 'username_id')
        images = Image.objects.filter(car=car)
        context = super().get_context_data(**kwargs)
        context['car'] = car
        context['images'] = images
        context['user_id'] = username_id
        return context

advertisements/templates/article.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="car-details-container">
        <div class="slider-container">
            <div class="slider">
                {% for image in images %}
                    <img src="{{ image.images.url }}" alt="Car" class="zoomable">
                {% endfor %}

            </div>
            <button class="prev-button" aria-label="Посмотреть предыдущий слайд">&lt;</button>
            <button class="next-button" aria-label="Посмотреть следующий слайд">&gt</button>
        </div>
        <script>const slider = document.querySelector('.slider');
        const prevButton = document.querySelector('.prev-button');
        const nextButton = document.querySelector('.next-button');
        const slides = Array.from(slider.querySelectorAll('img'));
        const slideCount = slides.length;
        let slideIndex = 0;

        prevButton.addEventListener('click', showPreviousSlide);
        nextButton.addEventListener('click', showNextSlide);

        function showPreviousSlide() {
            slideIndex = (slideIndex - 1 + slideCount) % slideCount;
            updateSlider();
        }

        function showNextSlide() {
            slideIndex = (slideIndex + 1) % slideCount;
            updateSlider();
        }

        function updateSlider() {
            slides.forEach((slide, index) => {
                if (index === slideIndex) {
                    slide.style.display = 'block';
                } else {
                    slide.style.display = 'none';
                }
            });
        }

        updateSlider();
        </script>


        <script>
            const images = document.querySelectorAll(".zoomable");
            const zoomOverlay = document.createElement("div");
            zoomOverlay.id = "zoom-overlay";
            zoomOverlay.style.display = "none";
            document.body.appendChild(zoomOverlay);
            const zoomedImage = document.createElement("img");
            zoomedImage.id = "zoomed-image";
            zoomedImage.alt = "Увеличенное изображение";
            zoomOverlay.appendChild(zoomedImage);

            images.forEach(image => {
                image.addEventListener("click", () => {
                    const src = image.getAttribute("src");
                    zoomedImage.setAttribute("src", src);
                    zoomOverlay.style.display = "block";
                });
            });

            zoomOverlay.addEventListener("click", () => {
                zoomOverlay.style.display = "none";
            });
        </script>


        <div class="car-details">
            <div class="car-info">
                <h2>{{ car.brand }} {{ car.model }} {{ car.generation }}</h2>
                <p class="car-price">Цена: {{ car.price }} $</p>

                <h3>Описание: </h3>

                <p class="car-description">
                    Цвет: {{ car.color }};
                    Пробег: {{ car.mileage }} км;
                    {{ car.release_year }} год;
                    {{ car.description }}
                </p>
                <h3>Дата публикации: {{ car.created_timestamp }}</h3>
            </div>
            {% if user.is_authenticated %}
                <div class="seller-info">
                    <h3>Контактная информация продавца:</h3>
                    <p><a style="color:blue; font-size: 18px" href="{% url 'users:profile' user_id %}">Профиль
                        продавца</a></p>
                    <p>Продавец: {{ car.username.first_name }} {{ car.username.last_name }}</p>
                    <p>Email: {{ car.username.email }}</p>
                    <p>Телефон: {{ car.username.phone_number }}</p>
                </div>


            {% else %}
                <h3><a style='color: blue' href="{% url 'users:login' %} ">Авторизуйтесь, чтобы увидеть контактные
                    данные продавца</a></h3>

            {% endif %}
        </div>
    </div>
{% endblock %}

advertisements/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <meta http-equiv="Content-Type">


</head>

<body>
<div class="header">
    <div class="header_section">
        <div class="header_item headerlogo">
            <a href="{% url 'advertisements:start' %}">CarSell</a>

        </div>

    </div>
    <div class="header_section">
        {% if user.is_authenticated %}
            <div class="header_item headerbutton"><a
                    href="{% url 'users:profile' user.id %}">Профиль: {{ user.username }}</a>
            </div>
            <div class="header_item headerbutton"><a href="{% url 'users:logout' %}">Выйти</a></div>
        {% else %}
            <div class="header_item headerbutton"><a href="{% url 'users:registration' %}">Регистрация</a></div>
            <div class="header_item headerbutton"><a href="{% url 'users:login' %}">Войти</a></div>
        {% endif %}

    </div>
</div>

{% block main %} {% endblock %}

advertisements/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <main>

        <div class="container">
            <div class="cards">
                {% for car in data %}

                    <a href="{% url 'advertisements:article' car.0.id %}" class="card">
                    <span class="card-header"
                          style="background-image: url({{ car.1.images.url }})">
                            <span class="card-title">
                                <h3>{{ car.0.brand }} {{ car.0.model }} {{ car.0.generation }}</h3>
                            </span>
                        </span>

                        <span class="card-summary">
                            {{ car.0.price }} $
                        </span>
                        <span class="card-meta">
                            Опубликовано: {{ car.0.created_timestamp }}
                        </span>
                    </a>
                {% endfor %}


            </div>
        </div>

    </main>
{% endblock %}
</body>

</html>

advertisements/templates/start.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <main style="justify-content: center; margin: auto auto 0 auto; display: block">
        <div class="center-img">
            <img src="https://sun6-22.userapi.com/s/v1/ig2/csXvVieHknU0E1Y415Rv-NRH8Ot9RJSdmIHgXSicAr9G78sgC6YuszrHtFYDDHPKQotKZCTR07D6AjjSb6lrn1Zt.jpg?size=1280x1280&quality=96&crop=0,0,1280,1280&ava=1"
                 alt="Логотип" class="logo">
            <div class="start-button">
                <a href="{% url 'advertisements:cars' %}">Начать подбор машины</a>
            </div>
        </div>

        <div class="start-form-container">
            <form class="sidebar-form" method="GET" action="{% url 'advertisements:cars' %}">
                <div class="start-adv-field">
                    <label for="brand">Марка машины:</label>
                    <select id="brand" name="brand">
                        <option value="">Выберите марку</option>
                    </select>
                </div>

                <div class="start-adv-field">
                    <label for="model">Модель:</label>
                    <select id="model" name="model">
                        <option value="">Выберите модель</option>
                    </select>
                </div>

                <div class="start-adv-field">
                    <label for="generations">Поколение:</label>
                    <select id="generations" name="generations">
                        <option value="">Выберите поколение</option>
                    </select>
                </div>

                <div class="start-adv-field">
                    <label for="release_year">Год выпуска:</label>
                    <input type="number" id="release_year" name="release_year">
                </div>

                <div class="start-adv-field">
                    <label for="mileage">Пробег (в км):</label>
                    <input type="number" id="mileage" name="mileage">
                </div>

                <div class="start-adv-field">
                    <label for="price_to">Цена от:</label>
                    <input type="number" id="price_from" name="price_from">
                </div>

                <div class="start-adv-field">
                    <label for="price_to">Цена до:</label>
                    <input type="number" id="price_to" name="price_to">
                </div>

                <div class="start-adv-field submit-field">
                    <input type="submit" value="Искать" href="{% url 'advertisements:cars' %}">
                </div>
            </form>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $(document).ready(function () {
            $.ajax({
                url: '{% url "users:get_car_brands" %}',
                dataType: 'json',
                success: function (data) {
                    var brandSelect = $('#brand');
                    brandSelect.empty();
                    {#console.log(data.brands)#}
                    brandSelect.append($('<option>', {
                        text: 'Выберите бренд',
                        disabled: true,
                        selected: true
                    }));
                    for (var i = 0; i < data.brands.length; i++) {
                        brandSelect.append($('<option>', {
                            value: data.brands[i].id,
                            text: data.brands[i].name
                        }));
                    }
                }
            });

            $('#brand').on('change', function () {
                var selectedBrand = $(this).val();

                var url = '{% url "users:get_models" %}';
                $.ajax({
                    url: url,
                    data: {
                        'brand_id': selectedBrand
                    },
                    dataType: 'json',
                    success: function (data) {
                        var modelSelect = $('#model');
                        modelSelect.empty();
                        modelSelect.append($('<option>', {
                            text: 'Выберите бренд',
                            disabled: true,
                            selected: true
                        }));
                        for (var i = 0; i < data.models.length; i++) {
                            modelSelect.append($('<option>', {
                                value: data.models[i].id,
                                text: data.models[i].name
                            }));
                        }
                    }
                });
            });


            $('#model').on('change', function () {
                var selectedModel = $(this).val();
                console.log(selectedModel);

                var url = '{% url "users:get_generations" %}';
                $.ajax({
                    url: url,
                    data: {
                        'model_id': selectedModel
                    },
                    dataType: 'json',
                    success: function (data) {
                        var generations = $('#generations');
                        console.log(data, 'data');
                        generations.empty();
                        generations.append($('<option>', {
                            text: 'Выберите поколение',
                            disabled: true,
                            selected: true
                        }));
                        for (var i = 0; i < data.generations.length; i++) {
                            console.log(data.generations[i], 'iii')
                            generations.append($('<option>', {
                                value: data.generations[i].id,
                                text: data.generations[i].name
                            }));
                        }

                    }
                });
            });
        });

        $(document).ready(function () {
            $('form.sidebar-form').submit(function (event) {
                var releaseYear = parseInt($('#release_year').val()) || 0;
                var minPrice = parseInt($('#price_from').val()) || null;
                var maxPrice = parseInt($('#price_to').val()) || null;
                console.log(minPrice, 'minPrice');
                console.log(maxPrice, 'maxPrice');

                if (releaseYear >= 2023) {
                    event.preventDefault();

                    alert('Год выпуска не может быть больше либо равен 2023');
                }
                if (minPrice && maxPrice && minPrice > maxPrice) {
                    event.preventDefault();

                    alert('Минимальная цена не может быть больше максимальной');
                }
            });
        });

    </script>

{% endblock %}